title: apocrypha
description: >
  A beautiful, fast, AMP-compliant Jekyll theme based on Tufte CSS.
url: "https://sariling-dwende.github.io"
paginate:	2 # The number of posts to show per page on your homepage
name: "Kael Espino"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
plugins:
  - jekyll-paginate
