title: apocrypha
description: >
  Thoughts unbound
url: "https://sariling-dwende.github.io"
baseurl: "/sarilingdwende.io"
paginate:	2 # The number of posts to show per page on your homepage
name: "Kael Espino"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
plugins:
  - jekyll-paginate
